### ISSUE TITLE
Provide artifacts upload tool as GHA

### ISSUE THREAD

**Issue by joao-paulo-parity** [paritytech/releng-scripts#12]
As explained in https://github.com/paritytech/release-engineering/issues/102#issuecomment-1308414160

> It should be rather trivial if the script is designed like we want the GHA to be. The idea behind using a GHA is also to shield us from the implementations details and whether we call the scripts direclty or use Docker for instance. All of those internal changes should not affect the repos using it.

> Keep in mind that the "user" will be at the very least polkadot, substrate, cumulus and this list will grow. So instead of having each of those directly call the scripts (which would be possible indeed), I think the extra layer of the GHA could be benficial for the maintenance and the ease of use in the repos.

Since we intend to have multiple scripts in the repository, it's necessary to think about how to provide them as GitHub Actions. One approach would be to have multiple `action.yml` in a single repository for each entrypoint, as done by e.g. https://github.com/github/codeql-action/blob/73ff862014865b27593070d3b63161a0012a39ec/analyze/action.yml#L80 (see https://github.com/orgs/community/discussions/24990 and https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-using-a-public-action-in-a-subdirectory). Thus the usage would be:

```yaml
- name: Use foo script
  uses: paritytech/releng-scripts/foo@master
  with:
    input: "bar"

- name: Use bar script
  uses: paritytech/releng-scripts/bar@master
```
